version: '3'
services:
  web:
    image: php:apache
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
    env_file:
      - .env